services:
  airflow-apiserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${AIRFLOW_UID:-1000}
        HOST_GID: ${AIRFLOW_GID:-1000}
    env_file:
      - .env
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${AIRFLOW_UID:-1000}
        HOST_GID: ${AIRFLOW_GID:-1000}
    env_file:
      - .env
  airflow-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${AIRFLOW_UID:-1000}
        HOST_GID: ${AIRFLOW_GID:-1000}
    env_file:
    - .env
  airflow-triggerer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${AIRFLOW_UID:-1000}
        HOST_GID: ${AIRFLOW_GID:-1000}
    env_file:
      - .env
